// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto
// Protobuf C++ Version: 4.26.0-dev

#include "order.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr make_order_response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : res_info_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        order_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ret_code_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR make_order_response::make_order_response(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct make_order_responseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR make_order_responseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~make_order_responseDefaultTypeInternal() {}
  union {
    make_order_response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 make_order_responseDefaultTypeInternal _make_order_response_default_instance_;

inline constexpr make_order_request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : goods_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        price_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR make_order_request::make_order_request(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct make_order_requestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR make_order_requestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~make_order_requestDefaultTypeInternal() {}
  union {
    make_order_request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 make_order_requestDefaultTypeInternal _make_order_request_default_instance_;
static ::_pb::Metadata file_level_metadata_order_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_order_2eproto = nullptr;
static const ::_pb::ServiceDescriptor*
    file_level_service_descriptors_order_2eproto[1];
const ::uint32_t
    TableStruct_order_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::make_order_request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::make_order_request, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::make_order_request, _impl_.goods_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::make_order_response, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::make_order_response, _impl_.ret_code_),
        PROTOBUF_FIELD_OFFSET(::make_order_response, _impl_.res_info_),
        PROTOBUF_FIELD_OFFSET(::make_order_response, _impl_.order_id_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::make_order_request)},
        {10, -1, -1, sizeof(::make_order_response)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_make_order_request_default_instance_._instance,
    &::_make_order_response_default_instance_._instance,
};
const char descriptor_table_protodef_order_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013order.proto\"2\n\022make_order_request\022\r\n\005p"
    "rice\030\001 \001(\005\022\r\n\005goods\030\002 \001(\t\"K\n\023make_order_"
    "response\022\020\n\010ret_code\030\001 \001(\005\022\020\n\010res_info\030\002"
    " \001(\t\022\020\n\010order_id\030\003 \001(\t2@\n\005Order\0227\n\nmake_"
    "order\022\023.make_order_request\032\024.make_order_"
    "responseB\003\200\001\001b\006proto3"
};
static ::absl::once_flag descriptor_table_order_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_order_2eproto = {
    false,
    false,
    221,
    descriptor_table_protodef_order_2eproto,
    "order.proto",
    &descriptor_table_order_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_order_2eproto::offsets,
    file_level_metadata_order_2eproto,
    file_level_enum_descriptors_order_2eproto,
    file_level_service_descriptors_order_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_order_2eproto_getter() {
  return &descriptor_table_order_2eproto;
}
// ===================================================================

class make_order_request::_Internal {
 public:
};

make_order_request::make_order_request(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:make_order_request)
}
inline PROTOBUF_NDEBUG_INLINE make_order_request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : goods_(arena, from.goods_),
        _cached_size_{0} {}

make_order_request::make_order_request(
    ::google::protobuf::Arena* arena,
    const make_order_request& from)
    : ::google::protobuf::Message(arena) {
  make_order_request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.price_ = from._impl_.price_;

  // @@protoc_insertion_point(copy_constructor:make_order_request)
}
inline PROTOBUF_NDEBUG_INLINE make_order_request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : goods_(arena),
        _cached_size_{0} {}

inline void make_order_request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.price_ = {};
}
make_order_request::~make_order_request() {
  // @@protoc_insertion_point(destructor:make_order_request)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void make_order_request::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.goods_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
make_order_request::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(make_order_request, _impl_._cached_size_),
              false,
          },
          &make_order_request::MergeImpl,
          &make_order_request::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void make_order_request::Clear() {
// @@protoc_insertion_point(message_clear_start:make_order_request)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.goods_.ClearToEmpty();
  _impl_.price_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* make_order_request::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2> make_order_request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_make_order_request_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::make_order_request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string goods = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(make_order_request, _impl_.goods_)}},
    // int32 price = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(make_order_request, _impl_.price_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(make_order_request, _impl_.price_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 price = 1;
    {PROTOBUF_FIELD_OFFSET(make_order_request, _impl_.price_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string goods = 2;
    {PROTOBUF_FIELD_OFFSET(make_order_request, _impl_.goods_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\5\0\0\0\0\0"
    "make_order_request"
    "goods"
  }},
};

::uint8_t* make_order_request::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:make_order_request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 price = 1;
  if (this->_internal_price() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_price(), target);
  }

  // string goods = 2;
  if (!this->_internal_goods().empty()) {
    const std::string& _s = this->_internal_goods();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "make_order_request.goods");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:make_order_request)
  return target;
}

::size_t make_order_request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:make_order_request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string goods = 2;
  if (!this->_internal_goods().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_goods());
  }

  // int32 price = 1;
  if (this->_internal_price() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_price());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void make_order_request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<make_order_request*>(&to_msg);
  auto& from = static_cast<const make_order_request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:make_order_request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_goods().empty()) {
    _this->_internal_set_goods(from._internal_goods());
  }
  if (from._internal_price() != 0) {
    _this->_impl_.price_ = from._impl_.price_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void make_order_request::CopyFrom(const make_order_request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:make_order_request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool make_order_request::IsInitialized() const {
  return true;
}

void make_order_request::InternalSwap(make_order_request* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.goods_, &other->_impl_.goods_, arena);
        swap(_impl_.price_, other->_impl_.price_);
}

::google::protobuf::Metadata make_order_request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_order_2eproto_getter,
                                   &descriptor_table_order_2eproto_once,
                                   file_level_metadata_order_2eproto[0]);
}
// ===================================================================

class make_order_response::_Internal {
 public:
};

make_order_response::make_order_response(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:make_order_response)
}
inline PROTOBUF_NDEBUG_INLINE make_order_response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : res_info_(arena, from.res_info_),
        order_id_(arena, from.order_id_),
        _cached_size_{0} {}

make_order_response::make_order_response(
    ::google::protobuf::Arena* arena,
    const make_order_response& from)
    : ::google::protobuf::Message(arena) {
  make_order_response* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.ret_code_ = from._impl_.ret_code_;

  // @@protoc_insertion_point(copy_constructor:make_order_response)
}
inline PROTOBUF_NDEBUG_INLINE make_order_response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : res_info_(arena),
        order_id_(arena),
        _cached_size_{0} {}

inline void make_order_response::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ret_code_ = {};
}
make_order_response::~make_order_response() {
  // @@protoc_insertion_point(destructor:make_order_response)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void make_order_response::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.res_info_.Destroy();
  _impl_.order_id_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
make_order_response::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(make_order_response, _impl_._cached_size_),
              false,
          },
          &make_order_response::MergeImpl,
          &make_order_response::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void make_order_response::Clear() {
// @@protoc_insertion_point(message_clear_start:make_order_response)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.res_info_.ClearToEmpty();
  _impl_.order_id_.ClearToEmpty();
  _impl_.ret_code_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* make_order_response::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 44, 2> make_order_response::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_make_order_response_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::make_order_response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 ret_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(make_order_response, _impl_.ret_code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(make_order_response, _impl_.ret_code_)}},
    // string res_info = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(make_order_response, _impl_.res_info_)}},
    // string order_id = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(make_order_response, _impl_.order_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ret_code = 1;
    {PROTOBUF_FIELD_OFFSET(make_order_response, _impl_.ret_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string res_info = 2;
    {PROTOBUF_FIELD_OFFSET(make_order_response, _impl_.res_info_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string order_id = 3;
    {PROTOBUF_FIELD_OFFSET(make_order_response, _impl_.order_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\10\10\0\0\0\0"
    "make_order_response"
    "res_info"
    "order_id"
  }},
};

::uint8_t* make_order_response::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:make_order_response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 ret_code = 1;
  if (this->_internal_ret_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_ret_code(), target);
  }

  // string res_info = 2;
  if (!this->_internal_res_info().empty()) {
    const std::string& _s = this->_internal_res_info();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "make_order_response.res_info");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string order_id = 3;
  if (!this->_internal_order_id().empty()) {
    const std::string& _s = this->_internal_order_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "make_order_response.order_id");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:make_order_response)
  return target;
}

::size_t make_order_response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:make_order_response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string res_info = 2;
  if (!this->_internal_res_info().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_res_info());
  }

  // string order_id = 3;
  if (!this->_internal_order_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_order_id());
  }

  // int32 ret_code = 1;
  if (this->_internal_ret_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_ret_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void make_order_response::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<make_order_response*>(&to_msg);
  auto& from = static_cast<const make_order_response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:make_order_response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_res_info().empty()) {
    _this->_internal_set_res_info(from._internal_res_info());
  }
  if (!from._internal_order_id().empty()) {
    _this->_internal_set_order_id(from._internal_order_id());
  }
  if (from._internal_ret_code() != 0) {
    _this->_impl_.ret_code_ = from._impl_.ret_code_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void make_order_response::CopyFrom(const make_order_response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:make_order_response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool make_order_response::IsInitialized() const {
  return true;
}

void make_order_response::InternalSwap(make_order_response* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.res_info_, &other->_impl_.res_info_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.order_id_, &other->_impl_.order_id_, arena);
        swap(_impl_.ret_code_, other->_impl_.ret_code_);
}

::google::protobuf::Metadata make_order_response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_order_2eproto_getter,
                                   &descriptor_table_order_2eproto_once,
                                   file_level_metadata_order_2eproto[1]);
}
// ===================================================================

const ::google::protobuf::ServiceDescriptor* Order::descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_order_2eproto);
  return file_level_service_descriptors_order_2eproto[0];
}

const ::google::protobuf::ServiceDescriptor* Order::GetDescriptor() {
  return descriptor();
}

void Order::make_order(::google::protobuf::RpcController* controller,
                         const ::make_order_request*, ::make_order_response*, ::google::protobuf::Closure* done) {
  controller->SetFailed("Method make_order() not implemented.");
  done->Run();
}

void Order::CallMethod(
    const ::google::protobuf::MethodDescriptor* method,
    ::google::protobuf::RpcController* controller,
    const ::google::protobuf::Message* request,
    ::google::protobuf::Message* response, ::google::protobuf::Closure* done) {
  ABSL_DCHECK_EQ(method->service(), file_level_service_descriptors_order_2eproto[0]);
  switch (method->index()) {
    case 0:
      make_order(controller,
             ::google::protobuf::internal::DownCast<const ::make_order_request*>(request),
             ::google::protobuf::internal::DownCast<::make_order_response*>(response), done);
      break;

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& Order::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::make_order_request::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
                  ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& Order::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::make_order_response::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
                  ->GetPrototype(method->output_type());
  }
}

Order_Stub::Order_Stub(::google::protobuf::RpcChannel* channel)
    : channel_(channel), owns_channel_(false) {}

Order_Stub::Order_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
    : channel_(channel),
      owns_channel_(ownership ==
                    ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}

Order_Stub::~Order_Stub() {
  if (owns_channel_) delete channel_;
}

void Order_Stub::make_order(::google::protobuf::RpcController* controller,
                              const ::make_order_request* request,
                              ::make_order_response* response, ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0), controller,
                       request, response, done);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_order_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
